### ISSUE TITLE
error: no member named 'tr1' in namespace 'std'

### ISSUE THREAD

**Issue by ryandesign** [neubig/lader#5]
lader does not build on OS X 10.9 Mavericks or later. The error is:

```
error: no member named 'tr1' in namespace 'std'
```

and

```
fatal error: 'tr1/unordered_map' file not found
```

The message is correct, in that there is no tr1 in OS X 10.9 and later: instead, there is the final, non-transitional implementation of those features. However, only the tr1 version exists in OS X 10.8 and earlier, so to support all versions of OS X, you should detect whether to use tr1 or not at configure time.

This was reported to the MacPorts project [here](https://trac.macports.org/ticket/47840) for version 0.1.5 and I verified it with the latest code in the repository as of right now.

**Comment by neubig** [comment]
Thanks for the report! I'll try to fix this soon.

**Comment by neubig** [comment]
I've fixed this error, and a bunch of other errors related to compiling with clang. I've also released a new version 0.1.6. Thanks for the report again!
